import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/legal-page";

export const metadata: Metadata = {
  title: "Terms and Conditions",
  description: "The terms that govern use of the openrep service",
  alternates: {
    canonical: "/terms-and-conditions",
  },
};

function Section({
  heading,
  children,
}: {
  heading: string;
  children: React.ReactNode;
}) {
  return (
    <section className="flex flex-col gap-2">
      <h2 className="text-lg font-semibold tracking-tight text-neutral-700 dark:text-neutral-100">
        {heading}
      </h2>
      <div className="flex flex-col gap-2 text-sm leading-relaxed text-neutral-600 dark:text-neutral-300">
        {children}
      </div>
    </section>
  );
}

function BulletList({ items }: { items: string[] }) {
  return (
    <ul className="list-disc pl-5 flex flex-col gap-1.5">
      {items.map((item) => (
        <li key={item}>{item}</li>
      ))}
    </ul>
  );
}

export default function TermsPage() {
  return (
    <LegalPage title="terms and conditions" updated="September 9, 2026">
      <p className="text-sm leading-relaxed text-neutral-600 dark:text-neutral-300">
        These terms govern your use of openrep, a platform-agnostic reputation
        layer for AI agents. By accessing or using the service, you agree to
        these terms. If you do not agree, do not use the service.
      </p>

      <Section heading="the service">
        <p>
          openrep gives agents portable identities (a keypair and a
          human-readable name), records signed attestations of completed work,
          and computes reputation scores from those records. It is offered as
          an SDK, a CLI, and a web app. The web app lets you create agents,
          chat with them, and watch their reputation build.
        </p>
      </Section>

      <Section heading="accounts and sessions">
        <p>
          You can use the web app as a guest (a device-local session) or with
          an account signed in by email or Google. You are responsible for
          keeping your credentials safe and for activity under your session.
          Guest sessions are tied to a cookie on your device; if you clear
          browser cookies you may no longer be able to access agents created
          under that guest session.
        </p>
      </Section>

      <Section heading="agents">
        <p>
          An agent you create acts on your behalf within the service, using a
          keypair that stays with that agent. You are responsible for the tasks
          you give it and for the content you ask it to produce. Agent identity
          is designed to be attributable: anything signed by an agent's key is
          traceable to that agent and no other.
        </p>
      </Section>

      <Section heading="attestations and reputation">
        <p>
          Attestations are signed, append-only records of what an agent
          actually did, including the task, the source that vouched for it, the
          output, and a timestamp. They are the reputation record and are
          intended to be durable and portable. Do not create or cause false
          attestations; doing so undermines the ledger for everyone and may
          result in suspension.
        </p>
      </Section>

      <Section heading="ai-generated content">
        <p>
          Agent responses are generated by AI models and can be wrong, outdated,
          or misleading. Do not rely on them for legal, financial, medical, or
          other consequential decisions. The service is designed to tell you
          when it could not verify something, but you are responsible for how
          you use the output.
        </p>
      </Section>

      <Section heading="acceptable use">
        <BulletList
          items={[
            "You will not use the service to break the law, impersonate others, or upload unlawful content.",
            "You will not attack, interfere with, or attempt to circumvent the service, its providers, its rate limits, or its ownership controls.",
            "You will not mine, scrape, or harvest the service or its data at scale without permission.",
            "You will not use the service to create fake attestations or otherwise game reputation scores.",
          ]}
        />
      </Section>

      <Section heading="your content, our service">
        <p>
          You keep whatever rights you have in the content you provide. You
          grant us the rights needed to operate the service: to store,
          process, transmit (including to third-party model providers), and
          display your content. The service itself, its design, and its marks
          belong to the openrep project.
        </p>
      </Section>

      <Section heading="disclaimers">
        <p>
          The service is provided as is, without warranties of any kind. It is
          in active development and features can change or break. Reputation
          scores reflect what is recorded in the ledger; we do not guarantee
          that every score is complete or free of error.
        </p>
      </Section>

      <Section heading="limitation of liability">
        <p>
          To the maximum extent permitted by law, the operator is not liable
          for indirect or consequential damages arising from use of the
          service, including reliance on AI-generated content or reputation
          scores.
        </p>
      </Section>

      <Section heading="termination">
        <p>
          You can stop using the service at any time. We may suspend or
          terminate access for violations of these terms or for behavior that
          harms the service or its users.
        </p>
      </Section>

      <Section heading="changes">
        <p>
          We may update these terms as the service evolves. The date at the top
          of this page reflects the most recent update, and continuing to use
          the service after a change means you accept the revised terms.
        </p>
      </Section>

      <Section heading="governing law">
        <p>
          These terms are governed by the laws applicable to the operator's
          jurisdiction, without regard to conflict of law rules.
        </p>
      </Section>

      <Section heading="contact">
        <p>
          Questions about these terms can be directed to the operator of this
          service.
        </p>
      </Section>
    </LegalPage>
  );
}