import type { AgentId, AgentManifest, KeyRotationRecord } from "./identity";
import type { Attestation, ToolCall } from "./attestation";
import type { RegisteredSource } from "./sources";

// an agent as persisted. everything in the manifest's portable fields except
// the owner public key is widened to nullable: rows created before the
// revocation pass genuinely have no owner key on record, and must never be
// revocable (the sdk fails closed on null with OWNER_KEY_MISSING). revokedAt
// is null until a valid, authorized revocation request marks the agent.
export interface AgentRecord extends Omit<AgentManifest, "ownerPublicKey"> {
  ownerPublicKey: string | null; // null only on pre-revocation-pass legacy rows
  revokedAt: string | null; // iso 8601 utc when revoked, null until then
  rowId?: number; // internal index assigned by storage at insert time, not part of the portable identity
}

// an attestation as persisted.
export interface AttestationRecord extends Attestation {
  rowId: number; // internal index
  // optional idempotency key used for dedup. storage-internal like rowId,
  // never part of the portable signed Attestation. the composite unique
  // index on (agent_id, idempotency_key) in the concrete backend is the
  // authoritative guard; null or absent means no dedup applies.
  idempotencyKey?: string;
}

// pagination params for any list returning function.
export interface PaginationParams {
  cursor?: string;
  limit?: number;
}

// standard paginated result shape, used by storage, activity, and any list.
export interface Paginated<T> {
  items: T[];
  nextCursor: string | null;
}

// the sender of a chat message. the demo chat is one assistant reply per
// user message, so tool calls are carried on the assistant message rather
// than modeled as interleaved turns.
export type ChatRole = "user" | "assistant";

// a single persisted chat message. role is the sender side, content the
// literal text, toolsUsed the tool calls that accompanied this message
// (empty when the turn was pure text), timestamp the iso 8601 utc record
// time. attestationId links an assistant message to the signed attestation
// its turn produced; user messages and legacy rows carry null.
export interface ChatMessage {
  role: ChatRole;
  content: string;
  toolsUsed: ToolCall[];
  timestamp: string;
  attestationId?: string | null;
}

// a chat message with the ownership pair attached, the shape append paths
// carry. the pair is the enforced scope: chat history is addressed by
// (agent_id, owner_user_id), never by a bare session id, so an owner can
// never address another owner's session even if they knew its stored id
// (adversarial review: cross-owner access).
export interface ChatMessageRecord extends ChatMessage {
  agentId: AgentId;
  ownerUserId: string;
}

// a chat session as persisted: the storage-assigned id plus the ownership
// pair and created-at timestamp. the id is generated by storage and is
// deliberately never exposed to callers as an addressing handle; every read
// and write resolves the pair.
export interface ChatSession {
  id: string;
  agentId: AgentId;
  ownerUserId: string;
  createdAt: string;
}

// storage contract. calling code depends only on this interface. the
// concrete implementation for this pass is sqlite, noted here so callers
// never import the backend directly and it can be swapped later.
export interface StorageAdapter {
  getAgent(agentId: AgentId): Promise<AgentRecord | null>;
  // name lookup used only for the optimistic collision check in createAgent.
  // the read is an optimization, never the source of truth for uniqueness.
  // the authoritative guard is a unique constraint on the name column in the
  // concrete backend, which also closes the check-then-write race between
  // two concurrent createAgent calls.
  getAgentByName(name: string): Promise<AgentRecord | null>;
  // persists an agent record. on a name-constraint violation (concurrent
  // create, or a caller supplied name that already exists) implementations
  // must throw an error whose `code` property is exactly "DUPLICATE_NAME",
  // matching the sdk's OpenRepErrorCode vocabulary. any other throw is
  // treated as a generic storage failure by callers. never logs or exposes
  // secrets or stack traces.
  saveAgent(record: AgentRecord): Promise<void>;
  // the actual revocation write, an internal storage method: performs the
  // UPDATE that sets revoked_at. called only from revokeAgent() in the sdk
  // layer, AFTER the caller's owner-key signature and replay-window checks
  // have already passed. storage itself never re-verifies signatures, that
  // is the sdk's job. when no row matches, implementations must throw an
  // error whose code property is exactly "AGENT_NOT_FOUND".
  revokeAgent(agentId: AgentId, revokedAt: string): Promise<void>;
  // the actual rotation write, an internal storage method: persists the
  // successor agent AND its key_rotations audit row in ONE atomic
  // transaction, so a partial rotation (new identity without lineage, or a
  // lineage pointing at nothing) can never be observed or persisted. called
  // only from rotateAgent() in the sdk layer, AFTER the caller's owner-key
  // signature, replay-window, and revocation-state checks have all passed.
  // storage never re-verifies signatures. on a name-constraint violation
  // implementations must throw DUPLICATE_NAME (createAgent-style, which the
  // sdk retry loop branches on) and on a public-key collision
  // DUPLICATE_PUBLIC_KEY; the transaction guarantees neither row persists
  // after such a rejection. any other throw is a generic storage failure.
  rotateAgent(record: AgentRecord, rotation: KeyRotationRecord): Promise<void>;
  // audit read for the rotation lineage: every key_rotation whose
  // old or new public key matches the agent id, newest first. not-found is
  // an empty array, never an error.
  getKeyRotations(agentId: AgentId): Promise<KeyRotationRecord[]>;
  getAttestations(agentId: AgentId, pagination?: PaginationParams): Promise<Paginated<AttestationRecord>>;
  // lookup used only for the optimistic idempotency check in attest(). like
  // getAgentByName, the read is an optimization, never the source of truth:
  // the authoritative dedup guard is a composite unique index on
  // (agent_id, idempotency_key) in the concrete backend, which also closes
  // the check-then-write race between two concurrent attest calls carrying
  // the same idempotency key.
  getAttestationByIdempotencyKey(agentId: AgentId, idempotencyKey: string): Promise<AttestationRecord | null>;
  saveAttestation(record: AttestationRecord): Promise<void>;
  getRegisteredSources(): Promise<RegisteredSource[]>;
  saveRegisteredSource(source: RegisteredSource): Promise<void>;
  // get-or-create the single chat session for an (agent, owner) pair. one
  // session per pair is enforced by a schema unique constraint, and the
  // returned id is storage generated (never caller supplied), so callers
  // have no session id to guess or leak. when the agent does not exist
  // implementations must throw an error whose code property is exactly
  // "AGENT_NOT_FOUND" (the session foreign key fires at insert).
  createChatSession(agentId: AgentId, ownerUserId: string, createdAt: string): Promise<ChatSession>;
  // read the pair's chat session. not-found returns null, never throws.
  getChatSession(agentId: AgentId, ownerUserId: string): Promise<ChatSession | null>;
  // append one message to the pair's chat session, atomically scoped by the
  // (agent_id, owner_user_id) pair: the stored session id is never an
  // addressing handle on this path. when the pair has no session
  // implementations must throw an error whose code property is exactly
  // "CHAT_SESSION_NOT_FOUND" (a message must never silently land in a
  // session the caller cannot see).
  appendChatMessage(message: ChatMessageRecord): Promise<void>;
  // all messages for the pair's session, oldest first. a missing session
  // reads as an empty array, never an error.
  getChatMessages(agentId: AgentId, ownerUserId: string): Promise<ChatMessage[]>;
  // every agent with a session-key row for this owner, oldest ownership
  // first. ownership is enforced here at query level: a caller can only ever
  // list agents it actually holds a session key row for, never a global
  // agent listing (adversarial review: idor / tenant scoping).
  listOwnedAgents(ownerUserId: string): Promise<AgentRecord[]>;
  // web account layer: users and their oauth/credentials account links.
  // these tables are web-owned (the sdk exposes the storage primitives, the
  // web auth layer owns the policy). not-found reads return null, never
  // throw. createUser/createAccountLink throw coded errors on constraint
  // violations: DUPLICATE_EMAIL on users.email, DUPLICATE_ACCOUNT on
  // (provider, provider_account_id), USER_NOT_FOUND when a link names a
  // missing user. email is normalized (trim + lowercase) by the caller
  // before it ever reaches storage.
  createUser(user: UserRecord): Promise<void>;
  getUserByEmail(email: string): Promise<UserRecord | null>;
  getUserById(id: string): Promise<UserRecord | null>;
  createAccountLink(link: AccountLink): Promise<void>;
  getAccountLink(provider: string, providerAccountId: string): Promise<AccountLink | null>;
  // move every owner-scoped row (session_keys, chat_sessions) from one
  // owner id to another in ONE transaction, so a guest->account merge can
  // never be observed half done (partial ownership split). idempotent by
  // construction: re-running with the same pair moves nothing. callers must
  // pass distinct ids; merging id to itself is a guarded no-op.
  mergeOwner(fromUserId: string, toUserId: string): Promise<void>;
}

// a web account. web-owned table; the sdk persists it, the web auth layer
// decides who may create one and with what credentials. passwordHash is
// null exactly when the account is oauth-only (google), and the web layer
// must refuse any password attempt against a null hash (no password claim
// on an oauth account).
export interface UserRecord {
  id: string; // uuid, web generated, never exposed to the browser
  email: string; // normalized lowercase, globally unique
  passwordHash: string | null; // scrypt envelope string, or null for oauth-only
  name: string | null;
  createdAt: string; // iso 8601 utc
}

// one identity link on an account (google sub, or the credentials pseudo
// provider). unique per (provider, provider_account_id): one external
// identity can never own two openrep accounts.
export interface AccountLink {
  id: string; // uuid, web generated
  userId: string; // references users.id
  provider: string; // "google" | "credentials"
  providerAccountId: string; // google sub, or the user id for credentials
  createdAt: string; // iso 8601 utc
}